class useData {
	getData = () => {
		const data = [
			{
				id: Math.floor(Math.random() * 99999) + 1,
				title: "OPERATOR",
				information: [
					{
						id: 1,
						phoneAssignment: "Operator",
						name: "",
						department: "Admin",
						phoneNumber: "9",
					},
				],
			},
			{
				id: Math.floor(Math.random() * 99999) + 1,
				title: "GROUND FLOOR AREA (G/F)",
				information: [
					{
						id: 2,
						phoneAssignment: "Information Area/Guard",
						name: "",
						department: "Information Area",
						phoneNumber: "110",
					},
					{
						id: 3,
						phoneAssignment: "Information Area/Annex",
						name: "",
						department: "Information Area",
						phoneNumber: "111",
					},
					{
						id: 4,
						phoneAssignment: "Showroom",
						name: "Edilyn",
						department: "Showroom",
						phoneNumber: "112",
					},
					{
						id: 5,
						phoneAssignment: "Showroom",
						department: "Showroom",
						name: "",
						phoneNumber: "113",
					},
					{
						id: 6,
						phoneAssignment: "SP Land",
						department: "SPLI",
						name: "",
						phoneNumber: "114",
					},
					{
						id: 7,
						phoneAssignment: "SP Land",
						department: "SPLI",
						name: "",
						phoneNumber: "115",
					},
					{
						id: 8,
						phoneAssignment: "E-Commerce/Shop Central",
						department: "E-Commerce/Shop Central",
						name: "",
						phoneNumber: "116",
					},
				],
			},
			{
				id: Math.floor(Math.random() * 99999) + 1,
				title: "2ND FLOOR AREA (2/F)",
				information: [
					{
						id: 9,
						phoneAssignment: "MIS",
						department: "MIS",
						name: "Kiko Tan (VP)",
						phoneNumber: "210",
					},
					{
						id: 10,
						phoneAssignment: "MIS - Master Data",
						department: "MIS",
						name: "Christian / Rema",
						phoneNumber: "211",
					},
					{
						id: 11,
						phoneAssignment:
							"MIS - SAP Team Functional",
						department: "MIS",
						name: "Albert / Cha / Harold",
						phoneNumber: "212",
					},
					{
						id: 12,
						phoneAssignment: "MIS",
						department: "MIS",
						name: "Al / Aries / Owen / Bill",
						phoneNumber: "213",
					},
					{
						id: 13,
						phoneAssignment:
							"MIS - Technical",
						department: "MIS",
						name: "Joey Sugcang / Jeff / Paul / Lance",
						phoneNumber: "214",
					},
					{
						id: 14,
						phoneAssignment: "MIS",
						department: "MIS",
						name: "Joebert Soberano (AVP - SAP)",
						phoneNumber: "215",
					},
					{
						id: 15,
						phoneAssignment: "MIS - SAP Team",
						department: "MIS",
						name: "Leizel / Neo / Alfre",
						phoneNumber: "216",
					},
					{
						id: 16,
						phoneAssignment: "Admin",
						department: "Admin",
						name: "Alma Garcia (VP)",
						phoneNumber: "225",
					},
					{
						id: 17,
						phoneAssignment: "Admin",
						department: "Admin",
						name: "Lynelle Santiago / Ryan David",
						phoneNumber: "226",
					},
					{
						id: 18,
						phoneAssignment: "Admin",
						department: "Admin",
						name: "Meann Inal / Joan Lee",
						phoneNumber: "227",
					},
					{
						id: 19,
						phoneAssignment: "SLAC Rice Sales",
						department: "SLAC Rice Sales",
						name: "",
						phoneNumber: "228",
					},
					{
						id: 20,
						phoneAssignment: "SLAC Rice Sales",
						department: "SLAC Rice Sales",
						name: "Tiffany Ngo (AVP)",
						phoneNumber: "229",
					},
					{
						id: 21,
						phoneAssignment: "SLAC Purchasing",
						department: "SLAC Purchasing",
						name: "Wilson / Arriane / Ma'am Tiff",
						phoneNumber: "230",
					},
					{
						id: 22,
						phoneAssignment:
							"SLAC Purchasing",
						department: "SLAC Purchasing",
						name: "Kristine / Charry / Rolland",
						phoneNumber: "231",
					},
					{
						id: 23,
						phoneAssignment: "SLAC Export",
						department: "SLAC Export",
						name: "Liza Guinto / Jennifer",
						phoneNumber: "232",
					},
				],
			},
			{
				id: Math.floor(Math.random() * 99999) + 1,
				title: "4TH FLOOR AREA (4/F)",
				information: [
					{
						id: 24,
						phoneAssignment: "President",
						department: "SGL",
						name: "Sir Gerry Lim (SGL)",
						phoneNumber: "410",
					},
					{
						id: 25,
						phoneAssignment: "President Secretary (SGL)",
						department: "SGL Sec",
						name: "Karol Fajardo",
						phoneNumber: "411",
					},
					{
						id: 26,
						phoneAssignment: "Galleon Logistics",
						department: "Galleon Logistics",
						name: "",
						phoneNumber: "414",
					},
					{
						id: 27,
						phoneAssignment: "ISG",
						department: "ISG",
						name: "John Paul",
						phoneNumber: "418",
					},
					{
						id: 28,
						phoneAssignment: "Tech Finance",
						department: "Tech Finance",
						name: "Kristine",
						phoneNumber: "419",
					},
					{
						id: 29,
						phoneAssignment: "SOS Sales",
						department: "SOS Sales",
						name: "Catherine",
						phoneNumber: "421",
					},
					{
						id: 30,
						phoneAssignment: "SOS Sales",
						department: "SOS Sales",
						name: "Joseph Guiao",
						phoneNumber: "422",
					},
					{
						id: 31,
						phoneAssignment: "SOS Sales",
						department: "SOS Sales",
						name: "",
						phoneNumber: "423",
					},
					{
						id: 32,
						phoneAssignment: "OEBG",
						department: "OEBG",
						name: "Elai",
						phoneNumber: "424",
					},
					{
						id: 33,
						phoneAssignment: "OEBG",
						department: "OEBG",
						name: "",
						phoneNumber: "425",
					},
					{
						id: 34,
						phoneAssignment: "Import - ",
						department: "Import",
						name: "Evelyn Lim (SVP)",
						phoneNumber: "430",
					},
					{
						id: 35,
						phoneAssignment: "Import",
						department: "Import",
						name: "Wingie / Nors",
						phoneNumber: "431",
					},
					{
						id: 36,
						phoneAssignment: "Import ",
						department: "Import",
						name: "Arsenio / Tess",
						phoneNumber: "432",
					},
					{
						id: 37,
						phoneAssignment: "SPRO Marketing",
						department: "SPRO Marketing",
						name: "",
						phoneNumber: "434",
					},
					{
						id: 38,
						phoneAssignment: "SPRO Marketing",
						department: "SPRO Marketing",
						name: "",
						phoneNumber: "435",
					},
					{
						id: 39,
						phoneAssignment: "SPRO Marketing",
						department: "SPRO Marketing",
						name: "",
						phoneNumber: "436",
					},
					{
						id: 40,
						phoneAssignment: "SPRO Marketing",
						department: "SPRO Marketing",
						name: "",
						phoneNumber: "437",
					},
					{
						id: 41,
						phoneAssignment: "SPRO Marketing",
						department: "SPRO Marketing",
						name: "",
						phoneNumber: "438",
					},
					{
						id: 42,
						phoneAssignment: "SPRO Marketing",
						department: "SPRO Marketing",
						name: "",
						phoneNumber: "439",
					},
					{
						id: 43,
						phoneAssignment: "Finance",
						department: "Finance",
						name: "Sally Uy (SVP)",
						phoneNumber: "440",
					},
					{
						id: 44,
						phoneAssignment: "Finance",
						department: "Finance",
						name: "Gina / Erwin / Erica",
						phoneNumber: "441",
					},
					{
						id: 45,
						phoneAssignment: "Finance MAD",
						department: "MAD Finance",
						name: "Ana / Arjay / Mean",
						phoneNumber: "442",
					},
					{
						id: 46,
						phoneAssignment: "Finance C&C",
						department: "FINANCE C&C",
						name: "Suzette / Natalie",
						phoneNumber: "443",
					},
					{
						id: 47,
						phoneAssignment: "Finance C&C",
						department: "FINANCE C&C",
						name: "Nellie",
						phoneNumber: "444",
					},
					{
						id: 48,
						phoneAssignment: "Tax Dept",
						department: "Tax",
						name: "Jesusa / Rose / Allyn",
						phoneNumber: "445",
					},
				],
			},
			{
				id: Math.floor(Math.random() * 99999) + 1,
				title: "5TH FLOOR AREA (5/F)",
				information: [
					{
						id: 49,
						phoneAssignment: "Treasury",
						department: "Treasury",
						name: "Maylen / Love",
						phoneNumber: "522",
					},
					{
						id: 50,
						phoneAssignment: "Treasury - Disbursement",
						department: "Treasury",
						name: "",
						phoneNumber: "524",
					},
					{
						id: 51,
						phoneAssignment: "Treasury - Loans",
						department: "Treasury",
						name: "Sandy / Karla / Angelica",
						phoneNumber: "523",
					},
					{
						id: 52,
						phoneAssignment: "Treasury - Remittance",
						department: "Treasury",
						name: "Vic",
						phoneNumber: "526",
					},
					{
						id: 53,
						phoneAssignment: "Treasury - Releasing",
						department: "Treasury",
						name: "Melody",
						phoneNumber: "527",
					},
					{
						id: 54,
						phoneAssignment:
							"EVP",
						department: "Finance - SVP",
						name: "Jocelyn Farnacio / Ext. Sec / Necitas",
						phoneNumber: "530",
					},
					{
						id: 55,
						phoneAssignment: "SLAC Finance",
						department: "SLAC Finance",
						name: "Mgr / Ext. Staff/ Edna",
						phoneNumber: "513",
					},
					{
						id: 56,
						phoneAssignment: "SLAC MAD",
						department: "SLAC MAD",
						name: "Elaine",
						phoneNumber: "514",
					},
					{
						id: 57,
						phoneAssignment: "SLAC Finance",
						department: "SLAC Finance",
						name: "",
						phoneNumber: "516",
					},
					{
						id: 58,
						phoneAssignment: "SLAC CNC",
						department: "SLAC CNC",
						name: "",
						phoneNumber: "518",
					},
					{
						id: 59,
						phoneAssignment: "SLAC Finance",
						department: "SLAC EVP - Finance",
						name: "Cathy Galura (EVP)",
						phoneNumber: "531",
					},
					{
						id: 60,
						phoneAssignment:
							"SLAC Seeds",
						department: "SLAC Seeds Operation",
						name: "Dona Lim (SVP) / John Dungca (VP)",
						phoneNumber: "532",
					},
					{
						id: 61,
						phoneAssignment: "SLAC Seeds Operation",
						department: "SLAC Seeds Operation",
						name: "Myra / Janine",
						phoneNumber: "534",
					},
					{
						id: 62,
						phoneAssignment: "SLAC Seeds Sales & Marketing",
						department: "SLAC Seeds Sales & Marketing",
						name: "Ria",
						phoneNumber: "536",
					},
					{
						id: 63,
						phoneAssignment: "SPRO Acctg - MAD",
						department: "SPRO Acctg MAD",
						name: "Joanna / Richa",
						phoneNumber: "537",
					},
					{
						id: 64,
						phoneAssignment: "SPRO Finance",
						department: "SPRO Finance - Herbert Baron",
						name: "Herbert Baron (Director)",
						phoneNumber: "538",
					},
					{
						id: 65,
						phoneAssignment: "SPRO Acctg / Operation",
						department: "SPRO Acctg / Operation",
						name: "Eunice",
						phoneNumber: "539",
					},
					{
						id: 66,
						phoneAssignment: "Atty's Office",
						department: "Atty's Office",
						name: "",
						phoneNumber: "511",
					},
				],
			},
			{
				id: Math.floor(Math.random() * 99999) + 1,
				title: "6TH FLOOR AREA (6/F)",
				information: [
					{
						id: 67,
						phoneAssignment: "Chairman / CEO",
						department: "SHL",
						name: "Sir Henry Lim (SHL)",
						phoneNumber: "610",
					},
					{
						id: 68,
						phoneAssignment: "SHL Secretary (1)",
						department: "SHL Secretary (1)",
						name: "",
						phoneNumber: "615",
					},
					{
						id: 69,
						phoneAssignment: "SHL Secretary (2)",
						department: "SHL Secretary (2)",
						name: "",
						phoneNumber: "616",
					},
					{
						id: 70,
						phoneAssignment: "Pantry",
						department: "Pantry",
						name: "",
						phoneNumber: "619",
					},
					{
						id: 71,
						phoneAssignment: "Board Room",
						department: "Board Room",
						name: "",
						phoneNumber: "618",
					},
					{
						id: 72,
						phoneAssignment: "Doc Malabanan",
						department: "Doc Malabanan",
						name: "",
						phoneNumber: "621",
					},
				],
			},
			{
				id: Math.floor(Math.random() * 99999) + 1,
				title: "GROUND FLOOR AREA - STERLING ANNEX (G/F)",
				information: [
					{
						id: 73,
						phoneAssignment: "PDD",
						department: "PDD - Manager",
						name: "Paul Hernandez",
						phoneNumber: "860",
					},
					{
						id: 74,
						phoneAssignment: "PDD",
						department: "PDD",
						name: "Reysan",
						phoneNumber: "861",
					},
					{
						id: 75,
						phoneAssignment: "PDD",
						department: "PDD",
						name: "Louie",
						phoneNumber: "862",
					},
				],
			},
			{
				id: Math.floor(Math.random() * 99999) + 1,
				title: "2ND FLOOR AREA - STERLING ANNEX (2/F)",
				information: [
					{
						id: 76,
						phoneAssignment: "HR Training",
						department: "HR",
						name: "Marcus / Roger / Carol / Japhet",
						phoneNumber: "871",
					},
					{
						id: 77,
						phoneAssignment: "HR",
						department: "HR",
						name: "Dione Putong (VP)",
						phoneNumber: "872",
					},
					{
						id: 78,
						phoneAssignment: "HR SLAC",
						department: "HR",
						name: "Eloisa / Mark / Martina / Racquel",
						phoneNumber: "873",
					},
					{
						id: 79,
						phoneAssignment: "HR SPPE",
						department: "HR",
						name: "Sheann / Dianne / Carla G. / Hannah",
						phoneNumber: "874",
					},
					{
						id: 80,
						phoneAssignment: "HR Galleon / SPRO / PSLI",
						department: "HR",
						name: "Mitch / Idz / Jessica / Kaye",
						phoneNumber: "875",
					},
				],
			},
			{
				id: Math.floor(Math.random() * 99999) + 1,
				title: "3RD FLOOR AREA - STERLING ANNEX (3/F)",
				information: [
					{
						id: 81,
						phoneAssignment: "SPRO - Engineering",
						department: "SP Propertied - Engineering",
						name: "",
						phoneNumber: "880",
					},
					{
						id: 82,
						phoneAssignment: "SPRO - BDD",
						department: "SP Propertied - BDD",
						name: "",
						phoneNumber: "881",
					},
					{
						id: 83,
						phoneAssignment: "VACANT - (Previously Openovate Office)",
						department: "Openovate Office",
						name: "",
						phoneNumber: "882",
					},
					{
						id: 84,
						phoneAssignment: "SGMP - Pharmacy",
						department: "SGMP - Pharmacy",
						name: "",
						phoneNumber: "884",
					},
					{
						id: 85,
						phoneAssignment: "Business Process",
						department: "Business Process",
						name: "",
						phoneNumber: "886",
					},
					{
						id: 86,
						phoneAssignment: "Audit",
						department: "Audit",
						name: "",
						phoneNumber: "887",
					},
					{
						id: 87,
						phoneAssignment: "Audit",
						department: "Audit",
						name: "",
						phoneNumber: "888",
					},
				],
			},
			{
				id: Math.floor(Math.random() * 99999) + 1,
				title: "MARILAO OFFICE",
				information: [
					{
						id: 88,
						phoneAssignment: "PPIC / Whse",
						department: "PPIC / Whse",
						name: "",
						phoneNumber: "703",
					},
					{
						id: 89,
						phoneAssignment: "HR Marilao",
						department: "HR Marilao",
						name: "Marisa / Fe",
						phoneNumber: "704",
					},
					{
						id: 90,
						phoneAssignment: "Admin Production",
						department: "Admin",
						name: "",
						phoneNumber: "705",
					},
				],
			},
			{
				id: Math.floor(Math.random() * 99999) + 1,
				title: "MEYCAUAYAN OFFICE",
				information: [
					{
						id: 91,
						phoneAssignment: "HR / Admin",
						department: "HR / Admin",
						name: "Alice",
						phoneNumber: "706",
					},
					{
						id: 92,
						phoneAssignment: "SOS Meycauayan",
						department: "SOS Meycauayan",
						name: "",
						phoneNumber: "707",
					},
					{
						id: 93,
						phoneAssignment: "CDG Maycauayan",
						department: "CDG Maycauayan",
						name: "",
						phoneNumber: "708",
					},
				],
			},
			{
				id: Math.floor(Math.random() * 99999) + 1,
				title: "LUPON DAVAO OFFICE",
				information: [
					{
						id: 94,
						phoneAssignment: "LUPON DAVAO OFFICE",
						department: "LUPON DAVAO OFFICE",
						name: "",
						phoneNumber: "710",
					},
					{
						id: 95,
						phoneAssignment: "AMINAWAY",
						department: "AMINAWAY",
						name: "",
						phoneNumber: "712",
					},
				],
			},
			{
				id: Math.floor(Math.random() * 99999) + 1,
				title: "ESSI",
				information: [
					{
						id: 94,
						phoneAssignment: "",
						name: "Joan Lim-Chung",
						department: "PCD",
						phoneNumber: "801",
					},
					{
						id: 95,
						phoneAssignment: "Talent Acquisition",
						name: "Renin",
						department: "PCD",
						phoneNumber: "802",
					},
					{
						id: 96,
						phoneAssignment: "People Systems",
						name: "",
						department: "PCD",
						phoneNumber: "803",
					},
					{
						id: 97,
						phoneAssignment: "People Experience",
						name: "Admin",
						department: "PCD",
						phoneNumber: "804",
					},
					{
						id: 98,
						phoneAssignment: "Jeremy Lim",
						name: "EPIC",
						department: "PCD",
						phoneNumber: "807",
					},
					{
						id: 99,
						phoneAssignment: "EPIC",
						name: "",
						department: "PCD",
						phoneNumber: "808",
					},
					{
						id: 100,
						phoneAssignment: "EPIC",
						name: "",
						department: "PCD",
						phoneNumber: "809",
					},
					{
						id: 101,
						phoneAssignment: "",
						name: "Rhoda Celestino",
						department: "CRS",
						phoneNumber: "812",
					},
					{
						id: 102,
						phoneAssignment: "CRS",
						name: "",
						department: "CRS",
						phoneNumber: "813",
					},
					{
						id: 103,
						phoneAssignment: "CRS",
						name: "",
						department: "CRS",
						phoneNumber: "814",
					},
					{
						id: 104,
						phoneAssignment: "CRS",
						name: "",
						department: "CRS",
						phoneNumber: "815",
					},
					{
						id: 105,
						phoneAssignment: "CBD",
						name: "",
						department: "CBD",
						phoneNumber: "818",
					},
					{
						id: 106,
						phoneAssignment: "CBD - Leasing",
						name: "",
						department: "CBD",
						phoneNumber: "819",
					},
					{
						id: 107,
						phoneAssignment: "CBD - Asse",
						name: "",
						department: "CBD",
						phoneNumber: "820",
					},
					{
						id: 108,
						phoneAssignment: "Corporatate Security Dept.",
						name: "",
						department: "CSD",
						phoneNumber: "823",
					},
					{
						id: 109,
						phoneAssignment: "Corporatate Security Dept.",
						name: "",
						department: "CSD",
						phoneNumber: "824",
					},
					{
						id: 110,
						phoneAssignment: "",
						name: "Sherly Ng",
						department: "SOD / SPG",
						phoneNumber: "827",
					},
					{
						id: 111,
						phoneAssignment: "SOD / SPG",
						name: "",
						department: "SOD / SPG",
						phoneNumber: "828",
					},
					{
						id: 112,
						phoneAssignment: "",
						name: "Toti Clarin",
						department: "SAPCD",
						phoneNumber: "831",
					},
					{
						id: 113,
						phoneAssignment: "Retail Systems Group",
						name: "",
						department: "SAPCD",
						phoneNumber: "832",
					},
					{
						id: 114,
						phoneAssignment: "Technical",
						name: "",
						department: "SAPCD",
						phoneNumber: "833",
					},
					{
						id: 115,
						phoneAssignment: "Fun Nation",
						name: "",
						department: "FN",
						phoneNumber: "834",
					},
					{
						id: 116,
						phoneAssignment: "Corpotate Audit Dept.",
						name: "",
						department: "CAD",
						phoneNumber: "837",
					},
					{
						id: 117,
						phoneAssignment: "Corpotate Audit Dept.",
						name: "",
						department: "CAD",
						phoneNumber: "838",
					},
					{
						id: 118,
						phoneAssignment: "VP - MCD",
						name: "",
						department: "MCD",
						phoneNumber: "841",
					},
					{
						id: 119,
						phoneAssignment: "Integration / MarCom",
						name: "",
						department: "MCD",
						phoneNumber: "842",
					},
					{
						id: 120,
						phoneAssignment: "Visual / Creative",
						name: "",
						department: "MCD",
						phoneNumber: "843",
					},
					{
						id: 121,
						phoneAssignment: "Central Purchasing Dept.",
						name: "",
						department: "CPas",
						phoneNumber: "846",
					},
					{
						id: 122,
						phoneAssignment: "Central Purchasing Dept.",
						name: "",
						department: "CPas",
						phoneNumber: "847",
					},
					{
						id: 123,
						phoneAssignment: "",
						name: "Annie Lagui",
						department: "FAD",
						phoneNumber: "850",
					},
					{
						id: 124,
						phoneAssignment: "Treasury",
						name: "",
						department: "FAD",
						phoneNumber: "851",
					},
					{
						id: 125,
						phoneAssignment: "Treasury",
						name: "Bert",
						department: "FAD",
						phoneNumber: "852",
					},
					{
						id: 126,
						phoneAssignment: "General Accounting",
						name: "Toran",
						department: "FAD",
						phoneNumber: "853",
					},
					{
						id: 127,
						phoneAssignment: "Payables",
						name: "",
						department: "FAD",
						phoneNumber: "854",
					},
					{
						id: 128,
						phoneAssignment: "Sales / MAD / Nueva Tax",
						name: "",
						department: "FAD",
						phoneNumber: "855",
					},
					{
						id: 129,
						phoneAssignment: "SJL",
						name: "",
						department: "EXEC",
						phoneNumber: "310",
					},
					{
						id: 130,
						phoneAssignment: "",
						name: "Grace Gilpo",
						department: "EXEC",
						phoneNumber: "311",
					},
					{
						id: 131,
						phoneAssignment: "",
						name: "Jason Lim / Weng Reunilla",
						department: "RMD",
						phoneNumber: "301",
					},
					{
						id: 132,
						phoneAssignment: "Receiving Area",
						name: "",
						department: "RMD",
						phoneNumber: "302",
					},
					{
						id: 133,
						phoneAssignment: "RMD - Mart One",
						name: "",
						department: "RMD",
						phoneNumber: "303",
					},
					{
						id: 134,
						phoneAssignment: "RMD - Mart One",
						name: "",
						department: "RMD",
						phoneNumber: "304",
					},
					{
						id: 135,
						phoneAssignment: "RMD - Mart One",
						name: "",
						department: "RMD",
						phoneNumber: "305",
					},
					{
						id: 136,
						phoneAssignment: "RMD - Mart One",
						name: "",
						department: "RMD",
						phoneNumber: "306",
					},
					{
						id: 137,
						phoneAssignment: "RMD - Mart One",
						name: "",
						department: "RMD",
						phoneNumber: "307",
					},
					{
						id: 138,
						phoneAssignment: "RMD - Mart One",
						name: "",
						department: "RMD",
						phoneNumber: "308",
					},
					{
						id: 139,
						phoneAssignment: "RMD - Expressions",
						name: "",
						department: "RMD",
						phoneNumber: "309",
					},
					{
						id: 140,
						phoneAssignment: "RMD - Expressions",
						name: "",
						department: "RMD",
						phoneNumber: "312",
					},
					{
						id: 141,
						phoneAssignment: "RMD - Expressions",
						name: "",
						department: "RMD",
						phoneNumber: "313",
					},
					{
						id: 142,
						phoneAssignment: "RMD - Expressions",
						name: "",
						department: "RMD",
						phoneNumber: "314",
					},
					{
						id: 143,
						phoneAssignment: "RMD - Expressions",
						name: "",
						department: "RMD",
						phoneNumber: "315",
					},
					{
						id: 144,
						phoneAssignment: "GPO",
						name: "",
						department: "GPO",
						phoneNumber: "318",
					},
					{
						id: 145,
						phoneAssignment: "MPC",
						name: "",
						department: "MPC",
						phoneNumber: "321",
					},
					{
						id: 146,
						phoneAssignment: "BPD",
						name: "",
						department: "BPD",
						phoneNumber: "314",
					},
					{
						id: 147,
						phoneAssignment: "OMNOM",
						name: "",
						department: "OMNOM",
						phoneNumber: "327",
					},
				],
			},
		];

		return data;
	};
}

export default new useData();
